### ISSUE TITLE
What about private/protected functions?

### ISSUE THREAD

**Issue by adaamz** [Kdyby/StrictObjects#1]
Hi,
why do you filter only public visibility and static access for suggestion? Bug can be inside class method too.
[Nette\ObjectMixin uses](https://api.nette.org/2.4/source-Utils.ObjectMixin.php.html#62) `get_class_methods` that can return private methods too.

**Comment by fprochazka** [comment]
Nette does the same thing. `ObjectMixin` uses `get_class_methods()` from the outside of class, so it returns only public methods (which is only an optimization imho).

The trait from this repo is imported directly to the affected class, so it's using it from within, which means it would return also private methods.

---

Also, I think the biggest benefit if the trait is that it provides useful info outside of current class, for example in templates. When you're directly in the file of the class, you most likely won't need suggestions of class internals, since the IDE is doing that.

---

If you do not agree, could you elaborate more please?

**Comment by adaamz** [comment]
But it is filtered for only public & static methods, isn't it?
https://github.com/Kdyby/StrictObjects/blob/master/src/Suggester.php#L32-L33

**Comment by Majkl578** [comment]
> so it returns only public methods (which is only an optimization imho)

I doubt that, optimizing error execution path doesn't make much sense to me.

> Also, I think the biggest benefit if the trait is that it provides useful info outside of current class, for example in templates. When you're directly in the file of the class, you most likely won't need suggestions of class internals

This makes sense, but the scope could be somehow detected from the call stack.

**Comment by fprochazka** [comment]
@CZechBoY yes, it's intentional. But @Majkl578 has a good point about detecting it from call stack.

**Comment by adaamz** [comment]
OK, I think that finding private/protected methods can be expensive (because you need to check the caller class etc).
