### ISSUE TITLE
PHP 7.0, Nette 3.0

### ISSUE THREAD

**Issue by MartkCz** [Kdyby/StrictObjects#2]
Can you create one version (2.0) for php 7.0 and above? There are many errors, when I use StrictObjects with Nette\Object

I can create PR

**Comment by Majkl578** [comment]
It should be 7.1, if anything. And Nette\Object is deprecated, don't use it.

**Comment by fprochazka** [comment]
You shouldn't use StrictObject and Nette\Object (or Nette\SmartObject) at the same time, but you might want to use it in classes that inherit Nette classes to make them more strict. But I wouldn't suggest that for for example components - it breaks them, they depend on events provided by Nette\SmartObject.

There won't aby any 7.0 versions of Kdyby packages, I'm skipping it completely, mainly because of nullable typehints.

I'm not in the phase of planning those 7.1 releases yet, but this package is standalone and it should be fairly easy to do the `v2.0`.

@MartkCz if you have the time, PR would be great, thanks :)

**Comment by Majkl578** [comment]
Actually, on the second thought, this package doesn't really need 7.1 support. It doesn't provide any interface nor does it provide any explicit functionality to be relied upon.
It's a good move to not release 7.0-compatible packages, would be a vaste of potential. 👍

**Comment by MartkCz** [comment]
I don't use Nette\SmartObject with StrictObjects (Nette\Object). I have problem with kdyby/translation, it uses StrictObjects in TranslationExtension.

IMHO it should be easy maintain both version (7.1 and 5.6).

Yes, I have time to create PR.

**Comment by fprochazka** [comment]
@MartkCz what kind of problem?

**Comment by MartkCz** [comment]
CompilerExtension uses SmartObject with type hinting and TranslationExtension uses Scream without type hinting => FATAL ERROR Declaration of ... must be compatible with ...

**Comment by fprochazka** [comment]
@MartkCz oh, I see, that is a problem. Good to know, thanks!

I will try to address this soon, but now keep in mind the packages are **not** compatible with Nette 3.0 yet.

**Comment by Majkl578** [comment]
I'll prepare a PR to upgrade to PHP 7.1. (edit: #4)
Anyway, Nette\SmartObject and this package should not be considered mutually compatible and definitely not used together...

**Comment by fprochazka** [comment]
I've made a mistake of adding it to the CompilerExtension. I'll removed it once I'll be releasing 7.1 versions for Nette 3.0

**Comment by Majkl578** [comment]
#5 & #6.
